# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_public_path: '/uploads/'
    images_directory: '%kernel.project_dir%/public/uploads/'
    locale: 'en'
    app.supported_locales: 'en|hr'
    supported_locales_list: ['en', 'hr']

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $targetDirectory: '%images_directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileService:
        public: true
        arguments:
            $targetDirectory: '%images_directory%'

    App\EventListener\LocaleListener:
        public: true
        arguments:
            $defaultLocale: '%kernel.default_locale%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setDefaultLocale, [ '%locale%' ] ]
            - [ setTranslationFallback, [ false ] ]

    App\Twig\TranslationExtension:
        arguments:
            $translator: '@translator'
            $session: '@session'
        tags:
            - { name: twig.extension }

    App\Twig\ContentTranslationExtension:
        tags:
            - { name: twig.extension }

    App\Service\ContentTranslationService:
        arguments:
            $parameterBag: '@parameter_bag'

    App\Service\PostManager:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $authorizationChecker: '@security.authorization_checker'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
